using System;
using System.Collections.Generic;
using System.Text;

namespace NuRender
{

 /// <summary>
 /// ErrorRegistration
 ///
 /// Generated by Lightning.Tools.ErrorConvert - July 3, 2021 19:34:00
 ///
 /// Registers errors for use with the new (internally based) Error Manager
 /// </summary>
 public static class ErrorRegistration
 {
     public static void RegisterErrors()
     {
            // todo: External-Internal Error Registration

#region NuRender Errors

         ErrorManager.RegisterError( new Error { Name = "NRCannotInitialiseSDL2Exception", Description = "!!this should be overridden in code!!", Severity = MessageSeverity.Error, Id = 138 });
         ErrorManager.RegisterError( new Error { Name = "NRInvalidWindowSettingsException", Description = "NuRender: Window.Settings is null and shouldn't be.", Severity = MessageSeverity.Error, Id = 139 });
         ErrorManager.RegisterError( new Error { Name = "NRErrorCreatingNRWindowException", Description = "!!this should be overridden in code!!.", Severity = MessageSeverity.Error, Id = 139 });
         ErrorManager.RegisterError( new Error { Name = "NRErrorCreatingNRRendererException", Description = "!!this should be overridden in code!!.", Severity = MessageSeverity.Error, Id = 140 });
         ErrorManager.RegisterError( new Error { Name = "NRCannotCreateObjectWithInvalidTypeException", Description = "!!this should be overridden in code!!", Severity = MessageSeverity.Error, Id = 141 });
         ErrorManager.RegisterError( new Error { Name = "NRCannotCreateNonNRObjectException", Description = "!!this should be overridden in code!!", Severity = MessageSeverity.Error, Id = 142 });
         ErrorManager.RegisterError( new Error { Name = "NRUnknownErrorCreatingNRObjectException", Description = "!!this should be overridden in code!!", Severity = MessageSeverity.Error, Id = 143 });

#if !WINDOWS
         ErrorManager.RegisterError( new Error { Name = "NROnlyImplementedInWindowsException", Description = "!!this should be overridden in code!!", Severity = MessageSeverity.Error, Id = 144 });
#endif

         ErrorManager.RegisterError( new Error { Name = "NRCannotInitialiseSDL2ImageException", Description = "!!this should be overridden in code!!", Severity = MessageSeverity.Error, Id = 144 });
         ErrorManager.RegisterError( new Error { Name = "NRCannotInitialiseSDL2MixerException", Description = "!!this should be overridden in code!!", Severity = MessageSeverity.Error, Id = 145 });
         ErrorManager.RegisterError( new Error { Name = "NRCannotInitialiseSDL2TTFException", Description = "!!this should be overridden in code!!", Severity = MessageSeverity.Error, Id = 146 });
         ErrorManager.RegisterError( new Error { Name = "NRCannotLoadFontException", Description = "!!this should be overridden in code!!", Severity = MessageSeverity.Error, Id = 147 });
         ErrorManager.RegisterError( new Error { Name = "NRAttemptedToAccessNonexistentWindowException", Description = "!!this should be overridden in code!!", Severity = MessageSeverity.FatalError, Id = 148 });
         ErrorManager.RegisterError( new Error { Name = "NRAttemptedToPerformInvalidTestException", Description = "!!this should be overridden in code!!", Severity = MessageSeverity.FatalError, Id = 149 });
         ErrorManager.RegisterError( new Error { Name = "NRAttemptedToCreateInvalidPolygonException", Description = "!!this should be overridden in code!!", Severity = MessageSeverity.Error, Id = 150 });
         ErrorManager.RegisterError( new Error { Name = "NRUnimplementedFeatureException", Description = "!!this should be overridden in code!!", Severity = MessageSeverity.Error, Id = 151 });

            #endregion

            #region GBFX Errors
         ErrorManager.RegisterError(new Error { Name = "InvalidOpcodeException", Severity = MessageSeverity.Error, Description = "!!this should be overridden in code!", Id = 200 });
            #endregion
        }
    }
}
